import {StyleSheet, Dimensions} from 'react-native';
import {normalize} from 'react-native-elements';
const w = Dimensions.get('screen').width;
const h = Dimensions.get('screen').height;

// Default styles
const defaultStyles = StyleSheet.create({
  defaultTheme: {
    backgroundColor: '#000',
    fontFamily: 'notoserif',
    color: 'white',
    height: h,
  },
  flexContainer: {
    flexDirection: 'row',
    padding: 0,
    margin: 0,
  },
  underLineText: {color: 'white', textDecorationLine: 'underline'},
  centered: {
    width: w,
    height: normalize(h * 0.8),
    justifyContent: 'center',
    alignItems: 'center',
  },
  grayText: {
    paddingVertical: normalize(h * 0.01),
    color: '#9f9d9a',
    fontSize: normalize(12),
    width: normalize(w * 0.65),
    fontWeight: 'bold',
  },
  container: {
    width: w,
    paddingHorizontal: normalize(w * 0.1),
  },
  button: {
    flexDirection: 'row',
    backgroundColor: '#ff671d',
    width: '100%',
    textAlign: 'center',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: normalize(h * 0.012),
    borderRadius: normalize(4),
    marginVertical: normalize(w * 0.03),
  },
  tab: {
    backgroundColor: '#6C757D',
    height: h * 0.08,
    paddingVertical: h * 0.02,
    flex: 0.1,
  },
  tabItem: {
    borderRadius: normalize(10),
    alignItems: 'center',
    width: w * 0.2,
    height: h * 0.065,
    padding: normalize(5),
  },
  tabTitle: {
    fontSize: normalize(12),
    color: 'white',
    paddingVertical: h * 0.001,
  },
  tabIcon: {color: 'white', fontSize: normalize(18)},
  tabActiveItem: {
    color: '#FF671D',
    backgroundColor: '#FF671D',
    borderRadius: normalize(10),
    alignItems: 'center',
    width: w * 0.18,
    height: h * 0.065,
    padding: normalize(5),
  },
  error: {
    position: 'absolute',
    color: '#ff671d',
    bottom: -h * 0.28,
    alignSelf: 'center',
  },
  mainContainer: {
    width: w,
    paddingHorizontal: normalize(w * 0.06),
    marginVertical: normalize(h * 0.03),
  },
  verticalContainer: {
    paddingVertical: normalize(h * 0.02),
  },
  topContainer: {
    paddingTop: normalize(h * 0.02),
  },
  bottomContainer: {
    paddingBottom: normalize(h * 0.02),
  },
});
// Auth styles
const AuthStyles = StyleSheet.create({
  errorConatainer: {
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    height: h * 0.4,
  },
  AuthContainer: {
    marginTop: normalize(h * 0.1),
    marginHorizontal: normalize(w * 0.1),
  },
  AuthTextContainer: {
    width: normalize(w * 0.7),
    color: 'white',
    fontSize: normalize(30),
  },
  inputItem: {
    marginVertical: normalize(h * 0.01),
  },
  authText: {
    color: 'white',
    fontSize: normalize(13),
    marginVertical: normalize(h * 0.008),
  },
  authInput: {
    backgroundColor: '#2D2D2D',
    color: 'white',
    borderRadius: normalize(4),
    paddingHorizontal: normalize(w * 0.06),
    width: normalize(w * 0.8),
    borderWidth: 0,
  },
  Authskip: {
    color: 'white',
    paddingTop: normalize(h * 0.02),
  },
  authLink: {
    textDecorationLine: 'underline',
    color: 'white',
    fontSize: 10,
  },
  authLinkText: {color: 'white', fontSize: normalize(13)},
  authCheckBox: {
    width: normalize(w * 0.1),
    fontSize: 20,
    alignSelf: 'center',
    textAlign: 'center',
  },
  authButton: {
    backgroundColor: '#ff671d',
    width: normalize(w * 0.6),
    alignSelf: 'center',
    alignItems: 'center',
    paddingVertical: normalize(h * 0.012),
    borderRadius: normalize(5),
    marginTop: normalize(w * 0.08),
    marginVertical: normalize(w * 0.03),
  },
  authIcon: {
    height: normalize(h * 0.03),
    alignSelf: 'center',
    marginTop: normalize(h * 0.009),
    marginLeft: normalize(-w * 0.1),
  },
  facebookMediaBtn: {
    backgroundColor: '#3b5998',
    marginHorizontal: normalize(w * 0.01),
    paddingHorizontal: normalize(w * 0.01),
    paddingRight: normalize(w * 0.08),
    borderRadius: normalize(5),
  },
  googleMediaBtn: {
    backgroundColor: 'white',
    color: 'black',
    marginHorizontal: normalize(w * 0.01),
    paddingHorizontal: normalize(w * 0.01),
    paddingRight: normalize(w * 0.08),
    borderRadius: normalize(5),
  },
  mediaIcon: {
    marginHorizontal: normalize(w * 0.02),
  },
  signUpLink: {
    justifyContent: 'center',
    color: 'white',
    textDecorationLine: 'underline',
    alignSelf: 'center',
  },
  errorStyle: {
    color: '#FF671D',
    alignSelf: 'flex-start',
  },
  forgetPassword: {
    marginVertical: h * 0.03,
  },
});
const discover = StyleSheet.create({
  header: {
    backgroundColor: '#000',
    paddingHorizontal: normalize(w * 0.1),
    marginTop: normalize(h * 0.01),
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  headerTitle: {color: 'white', fontSize: normalize(22), fontWeight: 'bold'},
  headerIcon: {
    color: 'white',
    fontSize: normalize(20),
  },
  searchInput: {
    backgroundColor: 'white',
    width: normalize(w * 0.78),
    borderRadius: normalize(5),
    paddingLeft: normalize(50),
    height: h * 0.06,
    color: 'black',
  },
  searchIcon: {
    color: 'white',
    backgroundColor: '#000',
    padding: normalize(8),
    alignSelf: 'center',
    zIndex: 1,
    borderRadius: normalize(5),
    position: 'absolute',
    left: normalize(10),
  },
  card: {
    width: normalize(w * 0.37),
    backgroundColor: '#2D2D2D',
    padding: normalize(10),
    marginRight: normalize(18),
    marginTop: normalize(20),
    borderRadius: normalize(5),
  },
  cardTitle: {
    fontSize: normalize(16),
    color: 'white',
    fontWeight: 'bold',
    marginVertical: normalize(w * 0.02),
  },
  cardDesc: {
    color: '#9f9d9a',
  },
  title: {
    color: 'white',
    fontSize: normalize(14),
    fontWeight: 'bold',
    width: normalize(w * 0.62),
    alignSelf: 'center',
    paddingVertical: h * 0.02,
  },
  link: {
    marginTop: normalize(h * 0.02),
    color: '#FF671D',
  },
  categoryImageStyle: {
    width: normalize(w * 0.185),
    height: normalize(h * 0.08),
    borderRadius: normalize(4),
    marginRight: normalize(w * 0.02),
    backgroundColor: '#2D2D2D',
  },
  categoryTitle: {
    color: 'white',
    fontSize: normalize(12),
    paddingTop: normalize(h * 0.005),
  },
  selectedCategoryTitle: {
    color: '#FF671D',
    fontSize: normalize(12),
    paddingTop: normalize(h * 0.005),
  },
  ScrollHorizontal: {
    flexDirection: 'row',
    padding: 0,
    margin: 0,
  },
  artistItem: {
    backgroundColor: '#2D2D2D',
    borderRadius: normalize(5),
    height: 'auto',
    padding: normalize(3),
    overflow: 'hidden',
  },
  artistImage: {
    width: '100%',
    height: normalize(h * 0.19),
    borderRadius: normalize(5),
    overflow: 'hidden',
  },
  artisDesc: {
    paddingHorizontal: normalize(w * 0.03),
    height: h * 0.06,
  },
  artistTitle: {
    color: 'white',
    fontSize: 12,
    fontWeight: 'bold',
    marginTop: normalize(-h * 0.03),
  },
  artistDesc: {
    color: '#9f9d9a',
    fontSize: normalize(11),
  },
  artistIcon: {
    color: 'white',
    fontSize: 18,
    paddingHorizontal: normalize(5),
  },
  heartSection: {
    marginHorizontal: normalize(10),
    position: 'relative',
    bottom: normalize(h * 0.18),
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  artistCategory: {
    borderWidth: normalize(1),
    borderColor: '#FF671D',
    borderRadius: normalize(5),
    padding: normalize(w * 0.01),
    backgroundColor: '#FF671D33',
  },
  heart: {
    color: '#FF671D',
    borderWidth: normalize(1),
    borderColor: '#FF671D',
    alignSelf: 'center',
    textAlign: 'center',
    paddingHorizontal: normalize(10),
    paddingVertical: normalize(7),
    borderRadius: normalize(5),
    fontSize: normalize(14),
  },
  addToBooking: {
    marginTop: h * 0.28,
    backgroundColor: '#2D2D2D',
    width: w * 0.82,
    height: h * 0.5,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: normalize(5),
  },
  closeModal: {
    width: w * 0.82,
    alignItems: 'flex-end',
    paddingRight: w * 0.022,
    paddingBottom: w * 0.02,
  },
  addToBookinDetails: {
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    width: w * 0.82,
    paddingLeft: w * 0.05,
  },
  addToBookingNames: {
    width: w * 0.75,
    paddingBottom: h * 0.02,
    borderBottomColor: '#818181',
    borderBottomWidth: normalize(1),
    marginBottom: h * 0.02,
  },
  addToBookingBtnIcon: {
    backgroundColor: '#6C757D',
    padding: normalize(w * 0.02),
    width: w * 0.113,
    justifyContent: 'center',
    textAlign: 'center',
    borderRadius: normalize(5),
  },
  addToBookingBtnText: {
    color: 'white',
    fontSize: normalize(13),
    fontWeight: 'bold',
    paddingTop: w * 0.01,
    paddingLeft: w * 0.01,
  },
  addToBookingBtnContainer: {
    width: w * 0.75,
  },
  searchModal: {
    marginTop: h * 0.05,
    height: h,
    width: w * 0.99,
    backgroundColor: '#2D2D2D',
    borderRadius: normalize(10),
  },
  searchBody: {
    paddingHorizontal: w * 0.08,
  },
  searchHeader: {
    flexDirection: 'row',
    paddingVertical: w * 0.05,
  },
  searchHeaderTitle: {
    color: 'white',
    fontSize: normalize(16),
    fontWeight: 'bold',
    width: w * 0.8,
    textAlign: 'center',
  },
  searchSuggestion: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: h * 0.01,
  },
  searchSuggestionText: {
    color: '#FFFFFFB3',
    fontSize: normalize(13),
  },
  searchCategoryList: {
    paddingHorizontal: w * 0.08,
    paddingRight: w * 0.3,
  },
  searchCategory: {
    backgroundColor: '#FF671D',
    paddingHorizontal: w * 0.057,
    paddingVertical: h * 0.02,
    borderRadius: 10,
    opacity: 0.3,
    marginRight: w * 0.045,
  },
  searchCategoryText: {
    color: '#FF671D',
    fontWeight: 'bold',
    fontSize: normalize(14),
  },
  searchArtists: {
    marginBottom: h * 0.12,
    paddingHorizontal: w * 0.06,
    paddingRight: w * 0.5,
  },
});
const categories = StyleSheet.create({
  header: {
    backgroundColor: 'transparent',
    height: normalize(h * 0.05),
  },
  headerTitle: {
    color: 'white',
    fontSize: normalize(18),
  },
  headerIcon: {
    color: 'white',
    paddingLeft: normalize(w * 0.03),
    fontSize: normalize(18),
    width: w * 0.2,
  },
  headerIconLeft: {
    color: 'white',
    marginHorizontal: normalize(w * 0.09),
    fontSize: normalize(18),
  },
  categoryImage: {
    width: normalize(w / 2),
    height: normalize(h / 2),
    resizeMode: 'contain',
  },
  cardImageContainer: {
    justifyContent: 'flex-start',
    alignContent: 'center',
  },
  FlatListCurrent: {
    width: normalize(w * 0.5),
    height: normalize(h * 0.3),
    borderWidth: normalize(2),
    borderColor: '#FF671D',
    borderRadius: normalize(16),
    overflow: 'hidden',
  },
  FlatListContainer: {
    alignItems: 'center',
    width: normalize(w * 0.5),
    height: 'auto',
    marginHorizontal: normalize(w * 0.04),
    marginTop: normalize(h * 0.02),
  },
  flatListRow: {
    width: normalize(w),
    height: 'auto',
  },
  CategoryImage: {
    width: '100%',
    height: '100%',
    borderWidth: normalize(2),
    borderColor: '#FF671D',
    borderRadius: normalize(10),
    overflow: 'hidden',
  },
  categoryTitle: {
    color: '#FF671D',
    fontSize: normalize(22),
    fontWeight: 'bold',
  },
  CategoryImageGrediant: {
    width: '100%',
    height: '100%',
    borderRadius: normalize(10),
    overflow: 'hidden',
    opacity: 0.5,
  },
  dropdownContainer: {
    width: normalize(w * 0.38),
    height: normalize(h * 0.13),
    paddingLeft: normalize(5),
  },
  categoryDropdown: {
    backgroundColor: 'transparent',
    borderWidth: normalize(1),
    borderColor: '#FF671D',
    height: normalize(h * 0.04),
    borderRadius: normalize(3),
  },
  dropdownListItem: {
    height: normalize(h * 0.03),
  },
  dropdownItem: {color: '#FF671D', paddingHorizontal: normalize(w * 0.02)},
  dropdownItemIcon: {
    color: '#FF671D',
    paddingTop: normalize(5),
    fontSize: normalize(18),
    paddingHorizontal: normalize(5),
  },
  searchContainer: {
    position: 'relative',
    top: -70,
    marginHorizontal: normalize(5),
  },
});
const artist = StyleSheet.create({
  artistCoverPhote: {
    width: '100%',
    backgroundColor: '#6C757D',
    height: normalize(h * 0.4),
    position: 'absolute',
    zIndex: 0,
  },
  artistContent: {
    backgroundColor: '#2D2D2D',
    width: normalize(w * 0.96),
    borderTopRightRadius: normalize(20),
    borderTopLeftRadius: normalize(20),
    paddingBottom: normalize(h * 0.4),
  },
  artistDescription: {
    color: 'white',
    fontSize: 14,
  },
  artistLike: {
    flexDirection: 'row',
    borderBottomColor: '#6C757D',
    borderBottomWidth: normalize(1),
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  loveButton: {
    backgroundColor: '#FF671D33',
    borderRadius: normalize(5),
    padding: normalize(10),
    paddingHorizontal: normalize(25),
    marginRight: normalize(w * 0.06),
  },
  workImage: {
    width: normalize(w * 0.33),
    height: normalize(h * 0.15),
    backgroundColor: '#6C757D',
    borderRadius: normalize(6),
    marginLeft: normalize(w * 0.07),
  },
});
const profile = StyleSheet.create({
  ProfileContainer: {
    flexDirection: 'row',
    width: normalize(w),
    paddingHorizontal: normalize(w * 0.1),
    marginTop: normalize(30),
    justifyContent: 'flex-start',
  },
  profileLabel: {
    backgroundColor: 'white',
    padding: w * 0.03,
    borderRadius: 5,
  },
  profileImage: {
    backgroundColor: '#2D2D2D',
    paddingHorizontal: normalize(20),
    borderRadius: normalize(6),
    marginRight: normalize(10),
    justifyContent: 'center',
    alignItems: 'center',
    height: normalize(h * 0.08),
  },
  signInSection: {
    width: normalize(w * 0.6),
    justifyContent: 'flex-start',
  },
  signButton: {
    flexDirection: 'row',
    backgroundColor: '#ff671d',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: normalize(h * 0.012),
    borderRadius: normalize(4),
  },
  leftSwitch: {
    flexDirection: 'row',
    width: normalize(w * 0.89),
    justifyContent: 'flex-end',
    marginVertical: normalize(25),
  },
  ProfileItems: {
    flexDirection: 'row',
    width: normalize(w * 0.66),
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerTitle: {
    color: 'white',
    fontSize: 18,
    width: normalize(w * 0.5),
  },
  uploadPhoto: {
    color: '#ff671d',
    textDecorationLine: 'underline',
    marginTop: normalize(h * 0.02),
    fontSize: normalize(14),
  },
  recentEventNameList: {
    paddingHorizontal: normalize(w * 0.08),
    maxWidth: '100%',
  },
  recentEventName: {
    borderRadius: normalize(5),
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
    paddingVertical: normalize(h * 0.01),
    marginVertical: normalize(h * 0.01),
    marginHorizontal: normalize(w * 0.01),
    backgroundColor: '#6C757D',
    paddingHorizontal: w * 0.02,
  },
  selectedRecentEventName: {
    backgroundColor: '#FF671D',
  },
  bookingForMenu: {
    width: w,
    height: normalize(h * 0.19),
    backgroundColor: '#2D2D2D',
    justifyContent: 'flex-start',
  },
  bookingForItem: {
    flexDirection: 'row',
    width: normalize(w * 0.75),
    height: normalize(h * 0.13),
    borderRadius: normalize(10),
    backgroundColor: '#0D0D0D',
    marginHorizontal: normalize(w * 0.01),
    overflow: 'hidden',
    marginVertical: h * 0.002,
  },
  bookingForItemImage: {
    margin: normalize(w * 0.01),
    width: normalize(w * 0.28),
    height: normalize(h * 0.12),
    borderRadius: normalize(10),
    backgroundColor: '#2D2D2D',
  },
  bookingForItemContent: {
    width: normalize(w * 0.4),
    height: normalize(h * 0.13),
    padding: normalize(w * 0.02),
  },
  bookingForItemTitle: {
    color: 'white',
    fontSize: normalize(13),
    fontWeight: 'bold',
  },
  bookingForItemDesc: {
    color: 'white',
    fontSize: normalize(10),
  },
  bookingForItemCategory: {
    backgroundColor: '#FF671D',
    color: '#FF671D',
    opacity: 0.2,
    height: normalize(h * 0.029),
    position: 'absolute',
    left: normalize(w * 0.02),
    top: normalize(h * 0.009),
    borderRadius: normalize(5),
  },
  bookingForItemButton: {
    width: normalize(w * 0.38),
    borderRadius: normalize(5),
    borderWidth: normalize(1),
    borderColor: '#FF671D',
    padding: normalize(w * 0.02),
    marginVertical: normalize(h * 0.012),
    alignItems: 'center',
  },
  bookingForItemButtonAdded: {
    backgroundColor: '#FF671D',
    width: normalize(w * 0.38),
    borderRadius: normalize(5),
    borderWidth: normalize(1),
    borderColor: '#FF671D',
    padding: normalize(w * 0.02),
    marginVertical: normalize(h * 0.012),
    alignItems: 'center',
  },
  ArtistViewDetailsBtn: {
    backgroundColor: 'transparent',
    width: normalize(w * 0.4),
    borderRadius: normalize(5),
    borderWidth: normalize(1),
    borderColor: '#FF671D',
    padding: normalize(w * 0.02),
    marginVertical: normalize(h * 0.012),
    alignItems: 'center',
  },
  bookingEventNames: {
    width: w,
  },

  bookingHistory: {
    width: w * 0.85,
    marginVertical: h * 0.01,
    flexDirection: 'row',
    borderBottomColor: '#2D2D2D',
    borderWidth: normalize(1),
    paddingVertical: h * 0.01,
  },
  bookingHistoryImage: {
    width: normalize(w * 0.16),
    height: normalize(h * 0.08),
    borderRadius: 10,
    backgroundColor: '#6C757D',
  },
  bookingHistoryContent: {
    width: w * 0.5,
    paddingHorizontal: w * 0.01,
  },
  bookingHistoryArtistsLink: {
    width: w * 0.2,
    height: normalize(h * 0.08),
    color: 'white',
    paddingVertical: normalize(h * 0.025),
  },
  bookingHistoryArtists: {
    width: w * 0.85,
    padding: w * 0.02,
    marginTop: h * 0.02,
    marginHorizontal: w * 0.075,
    backgroundColor: '#2D2D2D',
    borderRadius: normalize(10),
  },
  submitArtistCard: {
    flexDirection: 'row',
    width: normalize(w * 0.82),
    height: normalize(h * 0.13),
    borderRadius: normalize(10),
    backgroundColor: '#2D2D2D',
    marginHorizontal: normalize(w * 0.01),
    overflow: 'hidden',
    marginVertical: h * 0.002,
  },
});

const Booking = StyleSheet.create({
  formContainer: {
    paddingVertical: normalize(h * 0.02),
  },
  screenLabel: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 12,
    paddingVertical: normalize(h * 0.01),
  },
  label: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 14,
    paddingTop: h * 0.01,
  },
  selectItem: {
    marginVertical: normalize(h * 0.02),
    paddingRight: normalize(w * 0.05),
    width: w * 0.5,
  },
  selectIcon: {
    fontSize: normalize(20),
    color: '#ff671d',
    paddingRight: normalize(w * 0.01),
  },
  Line: {
    borderBottomColor: '#6C757D',
    borderBottomWidth: normalize(1),
  },
});
const cart = StyleSheet.create({
  cartArtist: {
    flexDirection: 'row',
    width: normalize(w * 0.75),
    height: normalize(h * 0.13),
    borderRadius: normalize(10),
    marginHorizontal: normalize(w * 0.01),
    overflow: 'hidden',
    marginVertical: h * 0.002,
    borderBottomWidth: normalize(1),
    borderBottomColor: '#FFFFFFB3',
  },
  likeRemoveIcon: {
    paddingHorizontal: h * 0.003,
    paddingVertical: w * 0.01,
  },
  formContainer: {
    paddingLeft: w * 0.03,
  },
  selectItem: {
    paddingVertical: normalize(h * 0.005),
    width: w * 0.4,
    overflow: 'hidden',
  },
  authInput: {
    backgroundColor: '#0D0D0D',
    color: 'white',
    borderRadius: normalize(4),
    paddingHorizontal: normalize(w * 0.06),
    width: normalize(w * 0.73),
    borderWidth: 0,
  },
  contentWrapper: {
    borderBottomColor: '#FFFFFFB3',
    borderBottomWidth: normalize(1),
    paddingBottom: h * 0.01,
  },
  submitArtistBtn: {
    backgroundColor: '#ff671d',
    width: normalize(w * 0.8),
    alignSelf: 'center',
    alignItems: 'center',
    paddingVertical: normalize(h * 0.012),
    borderRadius: normalize(5),
    marginVertical: normalize(w * 0.02),
  },
  submitArtistIcon: {
    color: '#FF671D',
    fontSize: normalize(14),
    backgroundColor: 'white',
    alignSelf: 'center',
    padding: normalize(5),
    borderRadius: normalize(20),
    position: 'absolute',
    marginLeft: w * 0.45,
  },
  suggestedArtists: {
    paddingHorizontal: w * 0.06,
  },
});
const settings = StyleSheet.create({
  container: {
    width: w,
    paddingHorizontal: w * 0.06,
  },
  settingLabelText: {
    color: 'white',
    paddingHorizontal: w * 0.01,
    fontWeight: '500',
  },
  settingLabelGrayText: {
    color: '#6C757D',
    paddingLeft: w * 0.3,
  },
  AboutUs: {
    marginTop: h * 0.05,
    marginBottom: h * 0.03,
    backgroundColor: '#FF671D',
    borderRadius: normalize(10),
    width: w * 0.5,
    height: h * 0.07,
    color: 'white',
  },
  AboutUsText: {
    color: 'white',
    fontSize: normalize(25),
    fontWeight: 'bold',
    paddingVertical: w * 0.02,
    paddingLeft: w * 0.03,
  },
  AboutUsInfo: {
    color: '#6C757D',
  },
  ContactUsBtn: {
    flexDirection: 'row',
    backgroundColor: '#ff671d',
    alignItems: 'center',
    width: w * 0.5,
    justifyContent: 'center',
    paddingVertical: normalize(h * 0.018),
    borderRadius: normalize(4),
    marginVertical: normalize(h * 0.025),
  },
  SettingsContainer: {
    borderBottomColor: '#FFFFFFB3',
    borderBottomWidth: normalize(1),
    width: w * 0.8,
    marginHorizontal: normalize(w * 0.1),
    marginTop: normalize(h * 0.08),
  },
  settingsLogout: {
    backgroundColor: '#2D2D2D',
    padding: w * 0.03,
    borderRadius: 5,
    color: 'white',
  },
  modal: {
    marginTop: h * 0.28,
    backgroundColor: '#2D2D2D',
    width: w * 0.82,
    height: h * 0.26,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: normalize(5),
  },
  authModal: {
    marginTop: h * 0.28,
    backgroundColor: '#2D2D2D',
    width: w * 0.82,
    height: h * 0.3,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: normalize(5),
  },
  modalText: {
    width: w * 0.66,
    color: 'white',
    fontSize: normalize(16),
    fontWeight: 'bold',
    marginBottom: h * 0.01,
  },
  modlaBtnLogut: {
    flexDirection: 'row',
    backgroundColor: '#ff671d',
    alignItems: 'center',
    width: w * 0.66,
    justifyContent: 'center',
    paddingVertical: normalize(h * 0.018),
    borderRadius: normalize(4),
    marginVertical: normalize(h * 0.005),
  },
  modalBtnCancel: {
    flexDirection: 'row',
    backgroundColor: '#0D0D0D',
    alignItems: 'center',
    width: w * 0.66,
    justifyContent: 'center',
    paddingVertical: normalize(h * 0.018),
    borderRadius: normalize(4),
    marginVertical: normalize(h * 0.005),
  },
});
export const Default = StyleSheet.flatten({defaultStyles});
export const Auth = StyleSheet.flatten({defaultStyles, AuthStyles});
export const Discover = StyleSheet.flatten({defaultStyles, discover});
export const Categories = StyleSheet.flatten({defaultStyles, categories});
export const Styles = StyleSheet.flatten({
  defaultStyles,
  AuthStyles,
  discover,
  categories,
  artist,
  profile,
  Booking,
  cart,
  settings,
});
